# AndroidX - REQUIRED for all modern Android projects
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Gradle performance
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# KMP
kotlin.mpp.stability.nowarn=true
kotlin.mpp.androidSourceSetLayoutVersion=2
